version: "3"

services:
  mysql:
    #image: mysql/mysql-server:5.7.22
    # from https://hub.atomgit.com/repos/library/mysql
    image: hub.atomgit.com/library/mysql:5.7.43
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=dev
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
#    volumes:
#      - "mysql_vol:/var/lib/mysql"
    networks:
      - default
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      timeout: 20s
      interval: 1s
      retries: 20
